### PR TITLE
Extract Android TV Launcher activities

### PR DESCRIPTION
**Pull request by gshah30**

### CODE REVIEW

**Review by koral-- — APPROVED** [review]

**Comment by koral--** [comment]
@gshah30 LGTM but please add a sign-off in order for DCO check to pass.

**Comment by gshah30** [comment]
Thanks @koral-- 

will do some testing and ensure that the change is working as expected and let you know when I am ready to merge.

**Comment by gshah30** [comment]
NPM Test

**Comment by gshah30** [comment]
@koral-- how do I run the tests so that the check is passed ?
Tried running `npm test` locally. Does not work.

**Comment by koral--** [comment]
Closing and reopening to retrigger CI build.

**Comment by gshah30** [comment]
@koral-- can we release this change ? 

It should be available in my project when I run

`npm install @devicefarmer/adbkit-apkreader`

**Comment by koral--** [comment]
According to https://www.npmjs.com/package/@devicefarmer/adbkit-apkreader version 3.2.3 is released 4 days ago.
Does not it contain changes from this PR? 🤔

**Comment by gshah30** [comment]
Sorry my bad.
Had to delete `package-lock.json` in my project. The new code release is available now.

Thanks.

**Pull request merged**
